---

services:
  smtptest:
    build:
      context: tests/
      args:
        - UID
        - GID
    env_file:
      - .env
    volumes:
      - ./tests/results:/var/mail/
    networks:
      testnet:
        ipv4_address: 172.28.2.5
        aliases:
          - smtp.test

  badrelay:
    build:
      context: tests/
    networks:
      testnet:
        ipv4_address: 172.28.2.6
        aliases:
          - bad.relay
    command: smtpd -d

  opendkim:
    #dns: 172.28.2.5
    networks:
      testnet:
    volumes:
      - ./tests/opendkim.test.conf:/etc/opendkim.test.conf
      - ./tests/stubdns:/srv/stubdns

  app:
    dns: 172.28.2.5
    networks:
      testnet:
        ipv4_address: 172.28.2.1
    volumes:
      - ./tests/results:/tmp/test_mails

  amavis:
    dns: 172.28.2.5
    networks:
      testnet:

  outamavis:
    dns: 172.28.2.5
    networks:
      testnet:

  db:
    networks:
      testnet:

  policyd-rate-limit:
    networks:
      testnet:

  smtp:
    dns: 172.28.2.5
    networks:
      testnet:

  outsmtp:
    dns: 172.28.2.5
    networks:
      testnet:

  relay:
    dns: 172.28.2.5
    networks:
      testnet:

  watcher:
    networks:
      testnet:

  senderverifmilter:
    networks:
      testnet:

  mailpit:
    networks:
      testnet:
        aliases:
          - mailpit.test


networks:
  testnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.1.0/24
          gateway: 172.28.1.254
