---

services:
  # auto tests
  smtptest:
    build:
      context: tests/
    env_file:
      - .env
    networks:
      default:
        aliases:
          - smtp.test
    depends_on:
      - outsmtp
      - smtp
      - app
    volumes:
      - ./tests:/tests

  opendkim:
    volumes:
      - ./tests/opendkim.test.conf:/etc/opendkim.test.conf
      - ./tests/stubdns:/srv/stubdns
