---

services:
  db:
    ports:
      - $DB_EXPOSED_PORT:3306
    # log queries to a file
    # docker compose exec db tail -f /var/lib/mysql/general.log
    command: [
      "--general-log",
      "--general-log-file=general.log",
      "--default-authentication-plugin=mysql_native_password"
    ]

  app:
    build:
      context: app/
      dockerfile: Dockerfile.dev
      args:
        - UID
        - GID
    volumes:
      - ./app/:/var/www/agentj
      - ./tests/results:/tmp/test_mails
    dns: 172.28.2.5
    networks:
      default:
        ipv4_address: 172.28.2.1
    working_dir: /var/www/agentj

  watcher:
   image: node:18-alpine
   user: ${UID}:${GID}
   working_dir: /app
   volumes:
        - ./app:/app
   restart: unless-stopped
   command: /bin/sh -c "yarn install && yarn watch"

  senderverifmilter:
    build:
      context: senderverifmilter
      args:
        - UID
        - GID
    volumes:
      - ./senderverifmilter/:/app
    command: bash -c "pip install --user -r requirements.txt ; python -u main.py"

  mailpit:
    image: axllent/mailpit:v1.22
    ports:
      - $MAILPIT_WEB_PORT:8025
    environment:
      - TZ
      - MP_DATABASE=/data/mailpit.db
    volumes:
      - mailpit_data:/data
    networks:
      default:
        aliases:
          - mailpit.test

  smtptest:
    build:
      context: tests/
      args:
        - UID
        - GID
    env_file:
      - .env
    volumes:
      - ./tests/results:/var/mail/
    networks:
      default:
        ipv4_address: 172.28.2.5
        aliases:
          - smtp.test

  ldap:
    image: bitnamilegacy/openldap:2
    ports:
        - "1389:1389"
        - "1636:1636"
    environment:
        - LDAP_ROOT=dc=example,dc=com
        - LDAP_ADMIN_USERNAME=admin
        - LDAP_ADMIN_PASSWORD=secret
        - BITNAMI_DEBUG=true
    volumes:
        - ./ldap:/ldifs:z

  opendkim:
    volumes:
      - ./tests/opendkim.test.conf:/etc/opendkim.test.conf
      - ./tests/stubdns:/srv/stubdns

  smtp:
    dns: 172.28.2.5

  outsmtp:
    dns: 172.28.2.5

  amavis:
    dns: 172.28.2.5

  outamavis:
    dns: 172.28.2.5

  clamav:
    dns: 172.28.2.5

networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.1.0/24
          gateway: 172.28.1.254
volumes:
  mailpit_data:
