---

services:
  # auto tests
  smtptest:
    build:
      context: tests/
    env_file:
      - .env
    networks:
      default:
        aliases:
          - smtp.test
    depends_on:
      - outsmtp
      - smtp
      - app

  smtpfriend:
    build:
      context: tests/
    env_file:
      - .env
    networks:
      default:
        aliases:
          - smtp.friend
    depends_on:
      - smtptest
    command: sh /usr/local/sbin/testmail.sh 'smtp.friend' 26

