# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

wblist:
    path: /wblist/{type}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'sender_rules_index'
        permanent: true
        keepQueryParams: true
        ignoreAttributes: false

domain_wblist:
    path: /domain/{id}/wblist
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'domain_sender_rules_index'
        permanent: true
        keepQueryParams: true
        ignoreAttributes: false

group_wblist:
    path: /groups/wblist/{groupId}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'groups_rules_index'
        permanent: true
        keepQueryParams: true
        ignoreAttributes: false
