Background              no
Mode                    s
Socket                  inet:8892
UserID                  opendkim:opendkim
UMask                   007

InternalHosts           127.0.0.1
Canonicalization        relaxed/relaxed
SignatureAlgorithm      rsa-sha256
KeyTable                file:/etc/opendkim-final/KeyTable
SigningTable            refile:/etc/opendkim-final/SigningTable

RequireSafeKeys         yes
RequiredHeaders         yes
OversignHeaders         From
KeepAuthResults         yes
RemoveOldSignatures     no
SoftwareHeader          no

On-InternalError        tempfail
On-SignatureError       tempfail
On-Security             tempfail

Syslog                  no
