FROM debian:trixie-slim

SHELL [ "/bin/sh", "-e", "-c" ]

ARG UID
ARG GID

RUN userdel www-data
RUN groupadd -g $GID www-data
RUN useradd -u $UID -g $GID -d /var/www www-data
RUN mkdir -p /var/www ; chown -R www-data /var/www

RUN apt-get update -q --fix-missing && \
    apt-get -y install --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    composer \
    git \
    nodejs \
    php8.4 \
    php8.4-bz2 \
    php8.4-cli \
    php8.4-common \
    php8.4-curl \
    php8.4-fpm \
    php8.4-gd \
    php8.4-ldap \
    php8.4-intl \
    php8.4-mbstring \
    php8.4-mysql \
    php8.4-opcache \
    php8.4-xml \
    php8.4-zip \
    php8.4-xdebug \
    tzdata \
    yarnpkg \
    zip \
    cron \
    libssl3 \
    mariadb-client \
    nginx-light \
    openssl \
    perl \
    sudo \
    supervisor \
    tzdata

RUN mkdir -p /var/run/php/ && touch /var/run/php/php84-fpm.pid


COPY docker/files/docker-php-ext-xdebug.ini /etc/php/8.4/fpm/conf.d/docker-php-ext-xdebug.ini
COPY docker/conf/cron/agentj /etc/cron.d/agentj
COPY docker/conf/nginx/nginx.conf /etc/nginx/sites-enabled/default
COPY docker/conf/php-fpm/www.conf /etc/php/8.4/fpm/pool.d/www.conf
COPY docker/conf/supervisor/supervisord.conf /etc/supervisord.conf
COPY docker/setup-env.sh /setup-env.sh
COPY docker/entrypoint.sh /entrypoint.sh
COPY docker/entrypoint-worker.sh /entrypoint-worker.sh
COPY docker/files/amavisd-release /usr/local/bin/amavisd-release

EXPOSE 9000

ENTRYPOINT [ "/entrypoint.sh" ]
CMD ["supervisord", "-c", "/etc/supervisord.conf"]
