use = ["auth-results"];
skip_local = false;
headers_modify_mode = "override";

custom {
  auth-results = <<EOD
return function(task)
  local ar = require "lua_auth_results"
  local value = ar.gen_auth_results(task, ar.default_settings)
  return nil, { ["Authentication-Results"] = value }, { ["Authentication-Results"] = 0 }, {}
end
EOD;
}
