#!/bin/bash

SCRIPT_PATH=$(dirname $(realpath -s $0))
export COMPOSE_FILE=$SCRIPT_PATH/../docker-compose.yml

source $SCRIPT_PATH/../.env

docker compose exec db mysql -u $DB_USER -p$DB_PASSWORD "$@"
