security:
    # encoders:
    #     App\Entity\User: bcrypt
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        # use your user class name here

        App\Entity\User:
            # Use native password hasher, which auto-selects the best
            # possible hashing algorithm (starting from Symfony 5.3 this is "bcrypt")
            algorithm: bcrypt
  
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    # providers:
    #     #in_memory: { memory: ~ }
    #     database_users:
    #         entity: { class: App\Entity\User, property: username }
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    role_hierarchy:
        ROLE_USER: []
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        check:
            pattern: ^/check
            security:  false
        captcha:
            pattern: ^/captcha-handler
            security:  false
        main:
            lazy: true
#            provider: users_in_memory
            custom_authenticator:
             - App\Security\LoginFormAuthenticator
             - App\Security\OAuthAuthenticator
#            entry_point: security_login
            logout:
                path: app_logout
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                always_remember_me: true
            switch_user: { role: CAN_SWITCH_USER }
#            context: agentj

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
         - { path: ^/login, roles: PUBLIC_ACCESS }
         - { path: ^/connect, roles: PUBLIC_ACCESS }
         - { path: ^/portal, roles: PUBLIC_ACCESS }
         - { path: ^/admin, roles: [ROLE_ADMIN] }
         - { path: ^/policy/, roles: ROLE_SUPER_ADMIN }
         - { path: ^/domain, roles: ROLE_ADMIN }
         - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
