when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            release: '%app.agentj-version%'
        register_error_listener: false
        register_error_handler: false

    monolog:
        handlers:
            sentry:
                type: sentry
                level: !php/const Monolog\Logger::ERROR
                hub_id: Sentry\State\HubInterface
                fill_extra_context: true
                process_psr_3_messages: false
