when@prod:
    sentry:
        dsn: '%env(string:default::SENTRY_DSN)%'
        options:
            release: '%app.agentj-version%'
            # Add request headers, cookies, IP address and the authenticated user
            # see https://docs.sentry.io/platforms/php/data-management/data-collected/ for more info
            # send_default_pii: true
            ignore_exceptions:
                - 'Symfony\Component\ErrorHandler\Error\FatalError'
                - 'Symfony\Component\Debug\Exception\FatalErrorException'
                - 'Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException'
                - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'
        # If you are using Monolog, you also need this additional configuration to log the errors correctly:
        # https://docs.sentry.io/platforms/php/guides/symfony/integrations/monolog/
        register_error_listener: false
        register_error_handler: false

    monolog:
        handlers:
            sentry:
                type: service
                id: Sentry\Monolog\Handler

    services:
        Sentry\Monolog\Handler:
            arguments:
                $hub: '@Sentry\State\HubInterface'
                $level: !php/const Monolog\Logger::ERROR
                $fillExtraContext: true
