name: CI

on: [pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
      - run: composer install --no-scripts --no-cache

      - name: PHPStan Static Analysis
        run: ./vendor/bin/phpstan -v

  testmail:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        run: |
          cp .env.example .env
          sed -i "s|#UID=.*|UID=`id -u`|g" .env
          sed -i "s|#GID=.*|GID=`id -g`|g" .env

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        env:
          APP_ENV: dev
          SF_APP_SECRET: "thisisnotasecretaaaaaaaaaaaaaaaa"
          SF_TOKEN_ENCRYPTION_IV: "thisneitherbbbbb"
          SF_TOKEN_ENCRYPTION_SALT: "/and+neither+plz+gitguardiannnnnnnnnnnnnnnn="
          DOMAIN: agentj.local
        with:
          compose-file: |
            docker-compose.yml
            compose.dev.yml
            compose.test.yml
          up-flags: --build
          down-flags: --volumes

      - name: Run tests
        env:
          COMPOSE_FILE: docker-compose.yml:compose.dev.yml:compose.test.yml
        run: |
          docker compose exec -u www-data app ./docker/tests/testmail.sh
          exit $(cat `find tests/results -name '*.result'` | grep -c failed)
