name: CI

on: [pull_request]

jobs:
  linters:
    env:
      NO_DOCKER: "true"

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Setup env
        run: |
            cd ./app
            cp .env.example .env
            sed -i "s|\$AGENTJ_VERSION|dev|g" .env
            sed -i "s|\$SF_APP_ENV|dev|g" .env
            sed -i "s|\$SF_APP_SECRET|change-me|g" .env
            sed -i "s|\$SF_TOKEN_ENCRYPTION_IV|change-me|g" .env
            sed -i "s|\$SF_TOKEN_ENCRYPTION_SALT|change-me|g" .env
            sed -i "s|\$SF_SENTRY_DSN||g" .env
            sed -i "s|\$DB_NAME|agentj|g" .env
            sed -i "s|\$DB_USER|agentj|g" .env
            sed -i "s|\$DB_PASSWORD|secret|g" .env
            sed -i "s|\$DB_HOST|localhost|g" .env
            sed -i "s|\$DOMAIN|example.com|g" .env
            sed -i "s|\$APP_URL|http://example.com|g" .env
            sed -i "s|\$SMTP_FROM|example@example.com|g" .env
            sed -i "s|\$ENABLE_AZURE_OAUTH||g" .env
            sed -i "s|\$OAUTH_AZURE_CLIENT_ID||g" .env
            sed -i "s|\$OAUTH_AZURE_CLIENT_SECRET||g" .env
            sed -i "s|\$TRUSTED_PROXIES||g" .env
            sed -i "s|\$TZ|Europe/Paris|g" .env
            sed -i "s|\$DEFAULT_LOCALE|en|g" .env
            sed -i "s|\$HISTORY_RETENTION_DAYS|30|g" .env

      - name: Install the dependencies
        run: |
            cd ./app
            composer install

      - name: Run the linters
        run: make lint

  test_mail:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        run: |
          sudo apt-get update ; sudo apt-get install -y swaks
          make .env
          echo 'SCHEDULER_CONSOLIDATE_FREQUENCY="1 second"' >> .env
          echo 'SCHEDULER_AUTORELEASE_FREQUENCY="1 second"' >> .env

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v3
        with:
          compose-file: |
            docker-compose.yml
            compose.dev.yml
          up-flags: --build
          down-flags: --volumes

      - name: Run tests
        run: |
          ./tests/tests.sh
          exit $(cat `find tests/results -name '*.result'` | grep -c failed)

  test_app:
    env:
      COVERAGE: "--coverage-html ./coverage --coverage-text"
      TEST_RESULTS: "--log-junit test-results/junit.xml"
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: "true"

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        run: make .env

      - name: Run docker-compose
        uses: hoverkraft-tech/compose-action@v3
        with:
          compose-file: |
            docker-compose.yml
            compose.dev.yml
          up-flags: --build
          down-flags: --volumes

      # This is supposely done by the watcher when running docker compose up.
      # However, as it can take a bit longer than starting the tests, the first
      # test(s) can fail because it can't find the assets. This makes sure the
      # assets are there before running the tests.
      - name: Build assets
        run: |
          docker compose exec -u www-data watcher yarnpkg dev

      - name: Run tests
        run: |
          make test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
            job_summary: false
            check_run: false
            files: |
                ./app/test-results/**/*.xml
                ./app/test-results/**/*.trx
                ./app/test-results/**/*.json

      - name: Upload test artifacts
        if: (!cancelled())
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-artifacts
          path: |
            ./app/coverage/
            ./app/test-results/
