FROM nginx:alpine

LABEL maintainer="Sébastien Poher <sebastien.poher@probesys.com>"
LABEL name = "AgentJ app reverse proxy"
LABEL description = "Nginx reverse proxy for AgentJ web app"

COPY conf/nginx.conf /etc/nginx/conf.d/default.conf